[package]
name = "theta-mp4"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
mp4 = { git = "https://github.com/arukoh/mp4-rust.git", branch = "master", version = "0.14.0" }
serde = "1.0.210"
serde_json = "1.0.128"
