---
    name: CI
    on:
      workflow_dispatch:
      push:
        paths:
          - src/**
          - test/**
          - Cargo.*/**
    
    jobs:
      test:
        runs-on: ${{ matrix.job.os }}
        strategy:
          fail-fast: false
          matrix:
            job:
              # - { os: ubuntu-latest  , target: x86_64-unknown-linux-gnu       , use-cross: false }
              # - { os: ubuntu-latest  , target: x86_64-unknown-linux-musl      , use-cross: true  }
              # - { os: ubuntu-latest  , target: armv7-unknown-linux-gnueabihf  , use-cross: true  }
              # - { os: ubuntu-latest  , target: armv7-unknown-linux-musleabihf , use-cross: true  }
              # - { os: ubuntu-latest  , target: aarch64-unknown-linux-gnu      , use-cross: true  }
              # - { os: ubuntu-latest  , target: aarch64-unknown-linux-musl     , use-cross: true  }
              # - { os: macos-latest   , target: x86_64-apple-darwin            , use-cross: false }
              # - { os: macos-latest   , target: aarch64-apple-darwin           , use-cross: false }
              - { os: windows-latest , target: x86_64-pc-windows-msvc         , use-cross: false }
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: Extract crate information
            shell: bash
            run: |
              echo "PROJECT_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> $GITHUB_ENV
    
          - name: Install Rust toolchain
            uses: actions-rs/toolchain@v1
            with:
              toolchain: stable
              target: ${{ matrix.job.target }}
              override: true
              profile: minimal
    
          - name: Test
            uses: actions-rs/cargo@v1
            with:
              use-cross: ${{ matrix.job.use-cross }}
              command: test